# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GravityTools
                                 A QGIS plugin
 This plugin processes gravity data and calculates topo reductions
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-10-07
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Stavros Kampourakis
        email                : stavkamp@outlook.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os.path
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.core import QgsProject, Qgis, QgsVectorLayer, QgsFeatureRequest
from qgis.core import QgsCoordinateReferenceSystem
import numpy as np
# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .grav_tools_dialog import GravityToolsDialog



class GravityTools:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        #Use default constants
        self.grav_const = 6.67259 / (10**11)
        self.land_const = 2670
        self.sea_const = 1027
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GravityTools_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&GravityTools')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GravityTools', message)

    def select_output_file(self):
        """Get an output file for the program's results.

        This is called by the def run() function of this class
        """
        filename, _filter = QFileDialog.getSaveFileName(self.dlg,
         "Select output file", "",'*csv')
        self.dlg.out_dest_text.setText(filename)
    def select_input_topo_file(self):
        """Get and input file for the topo grid required in
        order to calculate topographic reductions.

        This is called but the def run() function of this class
        """
        filename, _filter = QFileDialog.getSaveFileName(self.dlg,
         "Select input topo grid file", "",'*csv')
        self.dlg.in_dest_topo.setText(filename)






    def consts_declare(self):
        """Declare the constants used in this plugin, through the
        'Declarations' tab in the plugin menu.

        If this is not used then the defaults exist in the __init__ as
        self.grav_const = 6.67259 / (10**11)
        self.land_const = 2670
        self.sea_const = 1027

        """
        self.grav_const = float(self.dlg.line_gravconst.text())
        self.land_const = float(self.dlg.line_landconst.text())
        self.sea_const = float(self.dlg.line_seaconst.text())
        self.iface.messageBar().pushMessage(
            "Declarations", "grav_const = " + str(self.grav_const) +
                "×10−11 m3 kg−1 s−2 " +  "land_const = " + str(self.land_const)
                + "×kg/m3 " + "sea_const = " + str(self.sea_const) + "×kg/m3",
            level=Qgis.Success, duration=5)



    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/grav_tools/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Process gravity stations'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&GravityTools'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the
        # plugin is started
        if self.first_start:
            self.first_start = False
            self.dlg = GravityToolsDialog()
            self.dlg.out_dest_but.clicked.connect(self.select_output_file)
            self.dlg.in_dest_but.clicked.connect(self.select_input_topo_file)
            self.dlg.butt_declare.clicked.connect(self.consts_declare)
        # Fetch the currently loaded layers
        layers = QgsProject.instance().layerTreeRoot().children()
        sph_l=[]
        for child in layers:
            if child.layer().providerType() == 'ogr':
                sph_l.append(child)
        
        # Clear the contents of the combo_stat/tcmeth from previous runs
        self.dlg.combo_stat.clear()
        self.dlg.combo_tcmeth.clear()
        #available methods
        methods = ['Bouguer only', 'TC quick']
        # Populate the combo_stat with names of all the loaded layers
        self.dlg.combo_stat.addItems([child.name() for child in sph_l])
        self.dlg.combo_tcmeth.addItems(methods)
        # show the dialog
        self.dlg.show()
        a = self.calculate()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            #pass
            filename = self.dlg.out_dest_text.text()
            with open(filename, 'w') as output_file:
                selectedLayerIndex = self.dlg.combo_stat.currentIndex()
                selectedLayer = layers[selectedLayerIndex].layer()
                fieldnames = [field.name() for field in selectedLayer.fields()]
                # write header
                line = ','.join(name for name in fieldnames) + '\n'
                output_file.write(line)
                # write feature attributes
                for f in selectedLayer.getFeatures():
                    line = ','.join(str(f[name]) for name in fieldnames) + '\n'
                    output_file.write(line)
    

    def calculate(self):
        """Method that performs all the calculations.


        """
        layers = QgsProject.instance().layerTreeRoot().children()
        selectedStatLayerIndex = self.dlg.combo_stat.currentIndex()
        selectedStatLayer = layers[selectedStatLayerIndex].layer()
        

        #1.REMEMBER TO PUT "IF" IN ORDER TO CHOOSE THE METHOD APPLIED


        #2.REMEMBER TO FIND HOW TO CREATE A NEW LAYER THAT WILL
        #HAVE THE BG FIELD INSIDE.
        mem_layer = QgsVectorLayer("Point?crs=epsg:4326")
        #INTAKE STAT LAYER DATA/PUT NEW FIELD BGPLATE/SAVE
        for station in selectedStatLayer.getFeatures():
            test = +1

            #3. remember to include progress bar somehow.
        return 1
            
    
    def calc_boug_plate(self,H_ortho):
        """Function thah calculates bouger plate correction for a sigle station.

        :param H_ortho: The orthometrical height of the station from the
            reference geoid.
        :type H_ortho: single
        """
        if H_ortho > 0:
            return (2 * np.pi() * self.grav_const *
             self.land_const * H_ortho) * (10 ** 5)
        elif H_ortho < 0:
            return (2 * np.pi() * self.grav_const *
             (self.sea_const - self.land_const) * (-1 * H_ortho)) * (10 ** 5)
        else:
            return 0
